### ISSUE TITLE
Přidání odkazu na mapy okrsků

### ISSUE THREAD

**Issue by dqd** [svobodni/okrsky#9]
Často se stává, že je zájemce o delegaci zmatený a neví, jaký okrsek je ten jeho. Proto doporučuji do registrace přidat odkaz na web https://volby.tmapy.cz/, kde se to dá jednoduše dohledat.

**Comment by kubicek** [comment]
Díky, hotovo 0cb732b347880371333d35b26af3a31e0e8799ab
